import { defineConfig } from 'vite';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
export default defineConfig({
    root: fileURLToPath(new URL('.', import.meta.url)), base: './', publicDir: false,
    // Generated by the preceding library build, not checked-in source.
    resolve: { alias: { '@compression-probe/library': path.join(fileURLToPath(new URL('../../../../artifacts/compression-library/', import.meta.url)), 'image-beautifier.es.js') } },
    build: { target: ['chrome111', 'edge111', 'firefox128', 'safari16.4'],
        outDir: fileURLToPath(new URL('../../../../artifacts/compression-consumer/', import.meta.url)), emptyOutDir: true },
});
